#!/usr/bin/env groovy

properties([
    buildDiscarder(logRotator(artifactDaysToKeepStr: '30', artifactNumToKeepStr: '50', daysToKeepStr: '30', numToKeepStr: '50')),
    parameters([string(defaultValue: '1', description: '需要产生的随机测试数据条数', name: 'data', trim: true)])
])

def label = "builder-${UUID.randomUUID().toString()}"
podTemplate(label: label, yaml: libraryResource('kubernetes/testdata.yaml')) {
    node(label) {
        container('slave') {
            sh 'robot -l NONE -r NONE -o NONE -v loop:${data} /opt'
            publishHTML([allowMissing: false, alwaysLinkToLastBuild: true, keepAll: true, reportDir: '', reportFiles: 'testdata.html', reportName: '测试数据', reportTitles: ''])
            archiveArtifacts allowEmptyArchive: true, artifacts: 'testdata.html'
        }
    }
}

